# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Edward\.qgis2\python\plugins\MilkMachine\ui_milkmachine.ui'
#
# Created: Sun Jul 13 22:45:46 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MilkMachine(object):
    def setupUi(self, MilkMachine):
        MilkMachine.setObjectName(_fromUtf8("MilkMachine"))
        MilkMachine.resize(533, 218)
        self.buttonboxOkCancel = QtGui.QDialogButtonBox(MilkMachine)
        self.buttonboxOkCancel.setGeometry(QtCore.QRect(260, 360, 171, 32))
        self.buttonboxOkCancel.setOrientation(QtCore.Qt.Horizontal)
        self.buttonboxOkCancel.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonboxOkCancel.setObjectName(_fromUtf8("buttonboxOkCancel"))
        self.txtFeedback = QtGui.QTextEdit(MilkMachine)
        self.txtFeedback.setGeometry(QtCore.QRect(160, 320, 171, 31))
        self.txtFeedback.setObjectName(_fromUtf8("txtFeedback"))
        self.chkActivate = QtGui.QCheckBox(MilkMachine)
        self.chkActivate.setGeometry(QtCore.QRect(360, 320, 171, 31))
        self.chkActivate.setObjectName(_fromUtf8("chkActivate"))
        self.lineEdit_ImportGPS = QtGui.QLineEdit(MilkMachine)
        self.lineEdit_ImportGPS.setGeometry(QtCore.QRect(160, 40, 271, 31))
        self.lineEdit_ImportGPS.setAutoFillBackground(False)
        self.lineEdit_ImportGPS.setDragEnabled(True)
        self.lineEdit_ImportGPS.setObjectName(_fromUtf8("lineEdit_ImportGPS"))
        self.line = QtGui.QFrame(MilkMachine)
        self.line.setGeometry(QtCore.QRect(10, 220, 511, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.buttonImportGPS = QtGui.QPushButton(MilkMachine)
        self.buttonImportGPS.setGeometry(QtCore.QRect(40, 40, 101, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/milkmachine/Import.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonImportGPS.setIcon(icon)
        self.buttonImportGPS.setObjectName(_fromUtf8("buttonImportGPS"))
        self.buttonDrawTrack = QtGui.QPushButton(MilkMachine)
        self.buttonDrawTrack.setEnabled(False)
        self.buttonDrawTrack.setGeometry(QtCore.QRect(40, 80, 101, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/milkmachine/pencil.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonDrawTrack.setIcon(icon1)
        self.buttonDrawTrack.setObjectName(_fromUtf8("buttonDrawTrack"))
        self.buttonExportTrack = QtGui.QPushButton(MilkMachine)
        self.buttonExportTrack.setGeometry(QtCore.QRect(40, 270, 101, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/milkmachine/Export.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonExportTrack.setIcon(icon2)
        self.buttonExportTrack.setObjectName(_fromUtf8("buttonExportTrack"))
        self.comboBox_export = QtGui.QComboBox(MilkMachine)
        self.comboBox_export.setGeometry(QtCore.QRect(160, 270, 271, 31))
        self.comboBox_export.setObjectName(_fromUtf8("comboBox_export"))
        self.buttonImport_audio = QtGui.QPushButton(MilkMachine)
        self.buttonImport_audio.setGeometry(QtCore.QRect(40, 120, 101, 31))
        self.buttonImport_audio.setIcon(icon)
        self.buttonImport_audio.setObjectName(_fromUtf8("buttonImport_audio"))
        self.lineEdit_InAudio1 = QtGui.QLineEdit(MilkMachine)
        self.lineEdit_InAudio1.setGeometry(QtCore.QRect(160, 119, 271, 31))
        self.lineEdit_InAudio1.setObjectName(_fromUtf8("lineEdit_InAudio1"))
        self.pushButton_clearAudio1 = QtGui.QPushButton(MilkMachine)
        self.pushButton_clearAudio1.setEnabled(False)
        self.pushButton_clearAudio1.setGeometry(QtCore.QRect(440, 120, 31, 31))
        self.pushButton_clearAudio1.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/milkmachine/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_clearAudio1.setIcon(icon3)
        self.pushButton_clearAudio1.setObjectName(_fromUtf8("pushButton_clearAudio1"))
        self.pushButton_Audio1 = QtGui.QPushButton(MilkMachine)
        self.pushButton_Audio1.setEnabled(False)
        self.pushButton_Audio1.setGeometry(QtCore.QRect(40, 170, 31, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/milkmachine/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Audio1.setIcon(icon4)
        self.pushButton_Audio1.setObjectName(_fromUtf8("pushButton_Audio1"))
        self.lcdNumber_Audio1_C = QtGui.QLCDNumber(MilkMachine)
        self.lcdNumber_Audio1_C.setGeometry(QtCore.QRect(120, 170, 131, 31))
        self.lcdNumber_Audio1_C.setSmallDecimalPoint(False)
        self.lcdNumber_Audio1_C.setDigitCount(8)
        self.lcdNumber_Audio1_C.setObjectName(_fromUtf8("lcdNumber_Audio1_C"))
        self.lcdNumber_Audio1_P = QtGui.QLCDNumber(MilkMachine)
        self.lcdNumber_Audio1_P.setGeometry(QtCore.QRect(400, 170, 81, 31))
        self.lcdNumber_Audio1_P.setObjectName(_fromUtf8("lcdNumber_Audio1_P"))
        self.lcdNumber_Audio1_D = QtGui.QLCDNumber(MilkMachine)
        self.lcdNumber_Audio1_D.setGeometry(QtCore.QRect(260, 170, 131, 31))
        self.lcdNumber_Audio1_D.setDigitCount(8)
        self.lcdNumber_Audio1_D.setObjectName(_fromUtf8("lcdNumber_Audio1_D"))
        self.label = QtGui.QLabel(MilkMachine)
        self.label.setGeometry(QtCore.QRect(145, 153, 101, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(MilkMachine)
        self.label_2.setGeometry(QtCore.QRect(401, 153, 81, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(MilkMachine)
        self.label_3.setGeometry(QtCore.QRect(280, 153, 111, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pushButton_stop1 = QtGui.QPushButton(MilkMachine)
        self.pushButton_stop1.setEnabled(False)
        self.pushButton_stop1.setGeometry(QtCore.QRect(80, 170, 31, 31))
        self.pushButton_stop1.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/milkmachine/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_stop1.setIcon(icon5)
        self.pushButton_stop1.setObjectName(_fromUtf8("pushButton_stop1"))
        self.pushButton_Audio1info = QtGui.QPushButton(MilkMachine)
        self.pushButton_Audio1info.setEnabled(False)
        self.pushButton_Audio1info.setGeometry(QtCore.QRect(480, 120, 31, 31))
        self.pushButton_Audio1info.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/milkmachine/question.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Audio1info.setIcon(icon6)
        self.pushButton_Audio1info.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Audio1info.setObjectName(_fromUtf8("pushButton_Audio1info"))

        self.retranslateUi(MilkMachine)
        QtCore.QObject.connect(self.buttonboxOkCancel, QtCore.SIGNAL(_fromUtf8("accepted()")), MilkMachine.accept)
        QtCore.QObject.connect(self.buttonboxOkCancel, QtCore.SIGNAL(_fromUtf8("rejected()")), MilkMachine.reject)
        QtCore.QMetaObject.connectSlotsByName(MilkMachine)

    def retranslateUi(self, MilkMachine):
        MilkMachine.setWindowTitle(_translate("MilkMachine", "MilkMachine", None))
        self.chkActivate.setText(_translate("MilkMachine", "Activate\n"
"(check)", None))
        self.lineEdit_ImportGPS.setToolTip(_translate("MilkMachine", "Raw GPS input file (from GPS unit)", None))
        self.buttonImportGPS.setToolTip(_translate("MilkMachine", "<html><head/><body><p>Browse to .gpx file. This will convert the .gpx to a .kml, then import the kml. Additionally, a GeoJSON file will also be created in the same directory.</p></body></html>", None))
        self.buttonImportGPS.setText(_translate("MilkMachine", "Import GPS", None))
        self.buttonDrawTrack.setToolTip(_translate("MilkMachine", "<html><head/><body><p>Draw the imported GPS track on the map. This will draw the .kml file that was imported.</p></body></html>", None))
        self.buttonDrawTrack.setText(_translate("MilkMachine", "Draw Track", None))
        self.buttonExportTrack.setToolTip(_translate("MilkMachine", "Export the selected track to any supported format", None))
        self.buttonExportTrack.setText(_translate("MilkMachine", "Export Track", None))
        self.buttonImport_audio.setToolTip(_translate("MilkMachine", "<html><head/><body><p>Browse to the .wav file that matches one of the GPS tracks in the table of contents. Once the .wav file is imported, select the point in the track (using the select tool) where the audio file should start to play.</p></body></html>", None))
        self.buttonImport_audio.setText(_translate("MilkMachine", "Import Audio 1", None))
        self.pushButton_clearAudio1.setToolTip(_translate("MilkMachine", "<html><head/><body><p>Clear the audio input box</p></body></html>", None))
        self.pushButton_Audio1.setToolTip(_translate("MilkMachine", "<html><head/><body><p>After selecting a point in the GPS track that matches the .WAV audio file, click play.  The VLC media player will launch, starting at the time within the audio file that matches the time within the point file (.kml). </p></body></html>", None))
        self.lcdNumber_Audio1_C.setToolTip(_translate("MilkMachine", "<html><head/><body><p>Local time as recorded by the audio device</p></body></html>", None))
        self.lcdNumber_Audio1_P.setToolTip(_translate("MilkMachine", "<html><head/><body><p>Position in the track that the audio file is currently playing at (seconds). This corresponds to the feature (point) ID.</p></body></html>", None))
        self.lcdNumber_Audio1_D.setToolTip(_translate("MilkMachine", "<html><head/><body><p>Duration that the audio has been playing. hh:mm:ss</p></body></html>", None))
        self.label.setToolTip(_translate("MilkMachine", "<html><head/><body><p>The clock time stamp on the audio file.</p></body></html>", None))
        self.label.setText(_translate("MilkMachine", "Audio Clock Time", None))
        self.label_2.setToolTip(_translate("MilkMachine", "<html><head/><body><p>Feature ID (FID) number. For point data layers, this is a automatic number that is generated by QGIS to indicate sequential point number from the &quot;starting point&quot; of the track. The numbering starts at 0</p></body></html>", None))
        self.label_2.setText(_translate("MilkMachine", "Feature ID (FID)", None))
        self.label_3.setToolTip(_translate("MilkMachine", "<html><head/><body><p>The duration into the audio file that is currently playing.</p></body></html>", None))
        self.label_3.setText(_translate("MilkMachine", "Duration Into Audio", None))
        self.pushButton_stop1.setToolTip(_translate("MilkMachine", "<html><head/><body><p>Stops and closes the VLC media player and audio file</p></body></html>", None))
        self.pushButton_Audio1info.setToolTip(_translate("MilkMachine", "<html><head/><body><p>Click for information about the current audio track</p></body></html>", None))

import resources_rc
